---
version: 1
interactions:
- request:
    body: ""
    form: {}
    headers:
      User-Agent:
      - google-api-go-client/0.5
      X-Goog-Api-Client:
      - gl-go/1.11.0-rc2 gccl/20180226
    url: https://www.googleapis.com/storage/v1/b/go-cloud-blob-test-bucket/o/does-not-exist?alt=json&prettyPrint=false
    method: DELETE
  response:
    body: '{"error":{"errors":[{"domain":"global","reason":"notFound","message":"No
      such object: go-cloud-blob-test-bucket/does-not-exist","debugInfo":"com.google.net.rpc3.RpcException:
      cloud.bigstore.ResponseCode.ErrorCode::OBJECT_NOT_FOUND: No such object: go-cloud-blob-test-bucket/does-not-exist\n\tat
      com.google.cloud.bigstore.common.BigstoreException.toRpc3Exception(BigstoreException.java:143)\n\tat
      com.google.cloud.bigstore.common.BigstoreException.throwRpc3OnError(BigstoreException.java:317)\n\tat
      com.google.cloud.bigstore.api.json.handlers.objects.DeleteObject.handleRequestReceived(DeleteObject.java:77)\n\tat
      com.google.cloud.bigstore.api.json.handlers.objects.DeleteObject.handleRequestReceived(DeleteObject.java:23)\n\tat
      com.google.cloud.bigstore.api.json.framework.RequestHandler.handle(RequestHandler.java:294)\n\tat
      com.google.cloud.bigstore.api.json.ObjectsDelegator.delete(ObjectsDelegator.java:113)\n\tat
      com.google.cloud.bigstore.isolation.RpcReceiver.lambda$processRequestAsync$4(RpcReceiver.java:203)\n\tat
      com.google.cloud.bigstore.isolation.AsyncExecutor.lambda$submit$0(AsyncExecutor.java:253)\n\tat
      com.google.common.context.ContextRunnable.runInContext(ContextRunnable.java:50)\n\tat
      com.google.common.context.ContextRunnable$1.run(ContextRunnable.java:39)\n\tat
      io.grpc.Context.run(Context.java:565)\n\tat com.google.tracing.CurrentContext.runInContext(CurrentContext.java:166)\n\tat
      com.google.tracing.GenericContextCallback.runInInheritedContextNoUnref(GenericContextCallback.java:72)\n\tat
      com.google.tracing.GenericContextCallback.runInInheritedContext(GenericContextCallback.java:64)\n\tat
      com.google.common.context.ContextRunnable.run(ContextRunnable.java:36)\n\tat
      java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat
      java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat
      java.lang.Thread.run(Thread.java:748)\nCaused by: com.google.cloud.bigstore.common.BigstoreException:
      No such object: go-cloud-blob-test-bucket/does-not-exist\n\tat com.google.cloud.bigstore.common.BigstoreException.throwOnError(BigstoreException.java:304)\n\tat
      com.google.cloud.bigstore.common.BigstoreException.throwRpc3OnError(BigstoreException.java:315)\n\t...
      16 more\n\ncom.google.api.server.core.Fault: ImmutableErrorDefinition{base=NOT_FOUND,
      category=USER_ERROR, cause=null, debugInfo=com.google.net.rpc3.RpcException:
      cloud.bigstore.ResponseCode.ErrorCode::OBJECT_NOT_FOUND: No such object: go-cloud-blob-test-bucket/does-not-exist\n\tat
      com.google.cloud.bigstore.common.BigstoreException.toRpc3Exception(BigstoreException.java:143)\n\tat
      com.google.cloud.bigstore.common.BigstoreException.throwRpc3OnError(BigstoreException.java:317)\n\tat
      com.google.cloud.bigstore.api.json.handlers.objects.DeleteObject.handleRequestReceived(DeleteObject.java:77)\n\tat
      com.google.cloud.bigstore.api.json.handlers.objects.DeleteObject.handleRequestReceived(DeleteObject.java:23)\n\tat
      com.google.cloud.bigstore.api.json.framework.RequestHandler.handle(RequestHandler.java:294)\n\tat
      com.google.cloud.bigstore.api.json.ObjectsDelegator.delete(ObjectsDelegator.java:113)\n\tat
      com.google.cloud.bigstore.isolation.RpcReceiver.lambda$processRequestAsync$4(RpcReceiver.java:203)\n\tat
      com.google.cloud.bigstore.isolation.AsyncExecutor.lambda$submit$0(AsyncExecutor.java:253)\n\tat
      com.google.common.context.ContextRunnable.runInContext(ContextRunnable.java:50)\n\tat
      com.google.common.context.ContextRunnable$1.run(ContextRunnable.java:39)\n\tat
      io.grpc.Context.run(Context.java:565)\n\tat com.google.tracing.CurrentContext.runInContext(CurrentContext.java:166)\n\tat
      com.google.tracing.GenericContextCallback.runInInheritedContextNoUnref(GenericContextCallback.java:72)\n\tat
      com.google.tracing.GenericContextCallback.runInInheritedContext(GenericContextCallback.java:64)\n\tat
      com.google.common.context.ContextRunnable.run(ContextRunnable.java:36)\n\tat
      java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat
      java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat
      java.lang.Thread.run(Thread.java:748)\nCaused by: com.google.cloud.bigstore.common.BigstoreException:
      No such object: go-cloud-blob-test-bucket/does-not-exist\n\tat com.google.cloud.bigstore.common.BigstoreException.throwOnError(BigstoreException.java:304)\n\tat
      com.google.cloud.bigstore.common.BigstoreException.throwRpc3OnError(BigstoreException.java:315)\n\t...
      16 more\n, domain=global, extendedHelp=null, httpHeaders={}, httpStatus=notFound,
      internalReason=Reason{arguments={}, cause=null, code=gdata.CoreErrorDomain.NOT_FOUND,
      createdByBackend=true, debugMessage=com.google.net.rpc3.RpcException: cloud.bigstore.ResponseCode.ErrorCode::OBJECT_NOT_FOUND:
      No such object: go-cloud-blob-test-bucket/does-not-exist\n\tat com.google.cloud.bigstore.common.BigstoreException.toRpc3Exception(BigstoreException.java:143)\n\tat
      com.google.cloud.bigstore.common.BigstoreException.throwRpc3OnError(BigstoreException.java:317)\n\tat
      com.google.cloud.bigstore.api.json.handlers.objects.DeleteObject.handleRequestReceived(DeleteObject.java:77)\n\tat
      com.google.cloud.bigstore.api.json.handlers.objects.DeleteObject.handleRequestReceived(DeleteObject.java:23)\n\tat
      com.google.cloud.bigstore.api.json.framework.RequestHandler.handle(RequestHandler.java:294)\n\tat
      com.google.cloud.bigstore.api.json.ObjectsDelegator.delete(ObjectsDelegator.java:113)\n\tat
      com.google.cloud.bigstore.isolation.RpcReceiver.lambda$processRequestAsync$4(RpcReceiver.java:203)\n\tat
      com.google.cloud.bigstore.isolation.AsyncExecutor.lambda$submit$0(AsyncExecutor.java:253)\n\tat
      com.google.common.context.ContextRunnable.runInContext(ContextRunnable.java:50)\n\tat
      com.google.common.context.ContextRunnable$1.run(ContextRunnable.java:39)\n\tat
      io.grpc.Context.run(Context.java:565)\n\tat com.google.tracing.CurrentContext.runInContext(CurrentContext.java:166)\n\tat
      com.google.tracing.GenericContextCallback.runInInheritedContextNoUnref(GenericContextCallback.java:72)\n\tat
      com.google.tracing.GenericContextCallback.runInInheritedContext(GenericContextCallback.java:64)\n\tat
      com.google.common.context.ContextRunnable.run(ContextRunnable.java:36)\n\tat
      java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat
      java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat
      java.lang.Thread.run(Thread.java:748)\nCaused by: com.google.cloud.bigstore.common.BigstoreException:
      No such object: go-cloud-blob-test-bucket/does-not-exist\n\tat com.google.cloud.bigstore.common.BigstoreException.throwOnError(BigstoreException.java:304)\n\tat
      com.google.cloud.bigstore.common.BigstoreException.throwRpc3OnError(BigstoreException.java:315)\n\t...
      16 more\n, errorProtoCode=NOT_FOUND, errorProtoDomain=gdata.CoreErrorDomain,
      filteredMessage=null, location=entity.resource_id.name, message=No such object:
      go-cloud-blob-test-bucket/does-not-exist, unnamedArguments=[]}, location=entity.resource_id.name,
      message=No such object: go-cloud-blob-test-bucket/does-not-exist, reason=notFound,
      rpcCode=404} No such object: go-cloud-blob-test-bucket/does-not-exist: com.google.net.rpc3.RpcException:
      cloud.bigstore.ResponseCode.ErrorCode::OBJECT_NOT_FOUND: No such object: go-cloud-blob-test-bucket/does-not-exist\n\tat
      com.google.cloud.bigstore.common.BigstoreException.toRpc3Exception(BigstoreException.java:143)\n\tat
      com.google.cloud.bigstore.common.BigstoreException.throwRpc3OnError(BigstoreException.java:317)\n\tat
      com.google.cloud.bigstore.api.json.handlers.objects.DeleteObject.handleRequestReceived(DeleteObject.java:77)\n\tat
      com.google.cloud.bigstore.api.json.handlers.objects.DeleteObject.handleRequestReceived(DeleteObject.java:23)\n\tat
      com.google.cloud.bigstore.api.json.framework.RequestHandler.handle(RequestHandler.java:294)\n\tat
      com.google.cloud.bigstore.api.json.ObjectsDelegator.delete(ObjectsDelegator.java:113)\n\tat
      com.google.cloud.bigstore.isolation.RpcReceiver.lambda$processRequestAsync$4(RpcReceiver.java:203)\n\tat
      com.google.cloud.bigstore.isolation.AsyncExecutor.lambda$submit$0(AsyncExecutor.java:253)\n\tat
      com.google.common.context.ContextRunnable.runInContext(ContextRunnable.java:50)\n\tat
      com.google.common.context.ContextRunnable$1.run(ContextRunnable.java:39)\n\tat
      io.grpc.Context.run(Context.java:565)\n\tat com.google.tracing.CurrentContext.runInContext(CurrentContext.java:166)\n\tat
      com.google.tracing.GenericContextCallback.runInInheritedContextNoUnref(GenericContextCallback.java:72)\n\tat
      com.google.tracing.GenericContextCallback.runInInheritedContext(GenericContextCallback.java:64)\n\tat
      com.google.common.context.ContextRunnable.run(ContextRunnable.java:36)\n\tat
      java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat
      java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat
      java.lang.Thread.run(Thread.java:748)\nCaused by: com.google.cloud.bigstore.common.BigstoreException:
      No such object: go-cloud-blob-test-bucket/does-not-exist\n\tat com.google.cloud.bigstore.common.BigstoreException.throwOnError(BigstoreException.java:304)\n\tat
      com.google.cloud.bigstore.common.BigstoreException.throwRpc3OnError(BigstoreException.java:315)\n\t...
      16 more\n\n\tat com.google.api.server.core.ErrorCollector.toFault(ErrorCollector.java:54)\n\tat
      com.google.api.server.rest.adapter.rosy.RosyErrorConverter.toFault(RosyErrorConverter.java:67)\n\tat
      com.google.api.server.rest.adapter.rosy.RosyHandler$2.call(RosyHandler.java:258)\n\tat
      com.google.api.server.rest.adapter.rosy.RosyHandler$2.call(RosyHandler.java:238)\n\tat
      com.google.api.server.core.util.CallableFuture.run(CallableFuture.java:62)\n\tat
      com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)\n\tat
      com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1143)\n\tat
      com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:963)\n\tat
      com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:731)\n\tat
      com.google.api.server.core.util.CallableFuture.run(CallableFuture.java:62)\n\tat
      com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)\n\tat
      com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1143)\n\tat
      com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:963)\n\tat
      com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:731)\n\tat
      com.google.api.server.core.util.CallableFuture.run(CallableFuture.java:62)\n\tat
      com.google.api.server.thread.ThreadTrackers$ThreadTrackingRunnable.run(ThreadTrackers.java:126)\n\tat
      com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:453)\n\tat
      com.google.api.server.server.CommonModule$ContextCarryingExecutorService$1.runInContext(CommonModule.java:846)\n\tat
      com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:460)\n\tat
      io.grpc.Context.run(Context.java:565)\n\tat com.google.tracing.CurrentContext.runInContext(CurrentContext.java:166)\n\tat
      com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:319)\n\tat
      com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:311)\n\tat
      com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:457)\n\tat
      com.google.gse.internal.DispatchQueueImpl$WorkerThread.run(DispatchQueueImpl.java:403)\n"}],"code":404,"message":"No
      such object: go-cloud-blob-test-bucket/does-not-exist"}}'
    headers:
      Alt-Svc:
      - quic=":443"; ma=2592000; v="44,43,39,35"
      Cache-Control:
      - private, max-age=0
      Content-Length:
      - "11589"
      Content-Type:
      - application/json; charset=UTF-8
      Date:
      - Fri, 26 Oct 2018 22:56:38 GMT
      Expires:
      - Fri, 26 Oct 2018 22:56:38 GMT
      Server:
      - UploadServer
      Vary:
      - Origin
      - X-Origin
      X-Guploader-Customer:
      - apiary_cloudstorage_metadata
      X-Guploader-Request-Result:
      - agent_rejected
      X-Guploader-Upload-Result:
      - agent_rejected
      X-Guploader-Uploadid:
      - AEnB2Uo-UWt0GdNDxBSVuroeYYp_MUt_7uZ4ebyJGFPdma1yvIX083bihHCjHPtryKvDZ1xguvoAyDicgdl3zaY7nBxTum3eGw
    status: 404 Not Found
    code: 404
    duration: ""
